# Generated by Django 5.0.3 on 2024-05-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_category_remove_tasks_categories_todolist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('to_do', 'to_do'), ('in_progress', 'in_progress'), ('done', 'done')], default='to_do', max_length=20),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2024-05-04'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2024-05-04'),
        ),
    ]
